export const ADD_QUESTION_ANSWER_TO_AUTHED_USER = "ADD_QUESTION_ANSWER_TO_AUTHED_USER"
export const RECEIVE_USERS = "RECEIVE_USERS"
export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS"
export const SET_AUTHED_USER = "SET_AUTHED_USER"
export const ADD_QUESTION = "ADD_QUESTION"
export const ADD_QUESTION_TO_AUTHED_USER = "ADD_QUESTION_TO_AUTHED_USER"
export const ADD_QUESTION_ANSWER = "ADD_QUESTION_ANSWER"
export const ADD_QUESTION_ANSWER_USER = "ADD_QUESTION_ANSWER_USER"




